### ISSUE TITLE
helm installation of orchestra fails, as secret does not contain configuration: How to create that secret?

### ISSUE THREAD

**Issue by johanneskastl** [OpenUnison/helm-charts#118]
I installed the openunison-operator using helm and then installed the orchestra portal using helm (as ouctl errors out, see other issue).

The openunison-orchestra pod starts, as soon as I create the `orchestra` secret manually (which in my case only contains the `AD_BIND_PASSWORD`). But apparently the pod expects the secret to contain a openunison.yaml file.

```
[2023-10-31 08:52:11,445][main] INFO  OpenUnisonOnUndertow - Starting OpenUnison on Undertow 1.0.37-2023072501
[2023-10-31 08:52:11,461][main] INFO  OpenUnisonOnUndertow - Parsing YAML : '/etc/openunison/openunison.yaml'  
Exception in thread "main" java.io.FileNotFoundException: /etc/openunison/openunison.yaml (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)                                                                                                                            
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)                                                                                                                  
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)      
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)                                                                                                                
        at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.main(OpenUnisonOnUndertow.java:124)
```

Unfortunately I have not found many hints in the documentation on how to create the secret manually. The only secret name mentioned was `orchestra-secrets-source` (but that is for ArgoCD).

Should this rather be an issue for the docs git repository?

**Comment by mlbiam** [comment]
> Unfortunately I have not found many hints in the documentation on how to create the secret manually. The only secret name mentioned was orchestra-secrets-source (but that is for ArgoCD).

in the `Create a Secret that will be used for storing secret information like passwords and shared secrets.` for manual configuraiton inthe documentation it details how to create the `orchestra-secrets-source` `Secret` - https://openunison.github.io/deployauth/#manual-deployment

**Comment by johanneskastl** [comment]
Thanks Marc. Is there any more documentation on what exactly needs to go into that secret? What kind of keys are expected? Or are there just the two, `K8S_DB_SECRET` and `unisonKeystorePassword`?
