### ISSUE TITLE
using oidc clientID as a secret is not working

### ISSUE THREAD

**Issue by sandeep-ongit** [OpenUnison/helm-charts#183]
I am trying to use **"oidc.client_id_is_secret: true"** so that openunison can fetch the clientID from the secret **"orchestra-secrets-source"**.
But it is not working as expected.
When i set this up, the orchestra pod is throwing the below error in logs.

`Caused by: java.lang.IllegalArgumentException: clientId is null or empty
        at com.microsoft.aad.msal4j.ParameterValidationUtils.validateNotBlank(ParameterValidationUtils.java:12)
        at com.microsoft.aad.msal4j.AbstractClientApplicationBase$Builder.<init>(AbstractClientApplicationBase.java:136)
        at com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.<init>(ConfidentialClientApplication.java:153)
        at com.microsoft.aad.msal4j.ConfidentialClientApplication$Builder.<init>(ConfidentialClientApplication.java:147)
        at com.microsoft.aad.msal4j.ConfidentialClientApplication.builder(ConfidentialClientApplication.java:143)
        at com.tremolosecurity.provisioning.core.providers.AzureADProvider.loadCredentials(AzureADProvider.java:608)
        at com.tremolosecurity.provisioning.core.providers.AzureADProvider.init(AzureADProvider.java:598)
        at com.tremolosecurity.provisioning.core.ProvisioningEngineImpl.addTarget(ProvisioningEngineImpl.java:957)
        at com.tremolosecurity.provisioning.core.ProvisioningEngineImpl.addDynamicTarget(ProvisioningEngineImpl.java:994)
        at com.tremolosecurity.provisioning.targets.LoadTargetsFromK8s.addObject(LoadTargetsFromK8s.java:60)
        at com.tremolosecurity.k8s.watch.K8sWatcher.initalRun(K8sWatcher.java:161)
        ... 14 more`

I verified the **"orchestra-secrets-source"** secret and the values looks perfect in it.
But when i manually specify the oidc.client_id in values file, the orchestra pod runs as expected with no issues.

**Comment by mlbiam** [comment]
can you please provide the output of `k get authchain enterprise-idp -n openunison -o yaml`?

**Comment by sandeep-ongit** [comment]
@mlbiam  - here it is.

```
apiVersion: openunison.tremolo.io/v1
kind: AuthenticationChain
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"openunison.tremolo.io/v1","kind":"AuthenticationChain","metadata":{"annotations":{"argocd.argoproj.io/sync-wave":"30"},"labels":{"app.kubernetes.io/component":"openunison-authchains","app.kubernetes.io/instance":"k8s-cls-2-ou","app.kubernetes.io/name":"openunison","app.kubernetes.io/part-of":"openunison"},"name":"enterprise-idp","namespace":"openunison"},"spec":{"authMechs":[{"name":"oidc","params":{"bearerTokenName":"oidcBearerToken","defaultObjectClass":"inetOrgPerson","forceAuthentication":"true","hd":"","issuer":"https://login.microsoftonline.com/[REDACTED]/v2.0/","jwtTokenAttributeName":"id_token","linkToDirectory":"false","lookupFilter":"(uid=${sub})","noMatchOU":"oidc","responseType":"code","scope":"openid email profile","uidAttr":"sub","userLookupClassName":"com.tremolosecurity.unison.proxy.auth.openidconnect.loadUser.LoadJWTFromAccessToken"},"required":"required","secretParams":[{"name":"secretid","secretKey":"OIDC_CLIENT_SECRET","secretName":"orchestra-secrets-source#[openunison.static-secret.suffix]"},{"name":"clientid","secretKey":"OIDC_CLIENT_ID","secretName":"orchestra-secrets-source"}]},{"name":"map","params":{"map":["uid|composite|${upn}","mail|composite|${email}","givenName|composite|${given_name}","sn|composite|${family_name}","displayName|composite|${name}","memberOf|user|roles"]},"required":"required"},{"name":"include","params":{"chainName":"azuread-load-groups"},"required":"required"},{"name":"jit","params":{"nameAttr":"uid","workflowName":"jitdb"},"required":"required"},{"name":"genoidctoken","params":{"idpName":"k8sidp","trustName":"kubernetes"},"required":"required"}],"level":20,"root":"o=Data"}}
  creationTimestamp: "2024-11-11T09:17:27Z"
  generation: 5
  labels:
    app.kubernetes.io/component: openunison-authchains
    app.kubernetes.io/instance: k8s-cls-2-ou
    app.kubernetes.io/name: openunison
    app.kubernetes.io/part-of: openunison
  name: enterprise-idp
  namespace: openunison
  resourceVersion: "642356"
  uid: 76708d48-c454-43fb-b626-fb115a4b1c9c
spec:
  authMechs:
  - name: oidc
    params:
      bearerTokenName: oidcBearerToken
      defaultObjectClass: inetOrgPerson
      forceAuthentication: "true"
      hd: ""
      issuer: https://login.microsoftonline.com/[REDACTED]/v2.0/
      jwtTokenAttributeName: id_token
      linkToDirectory: "false"
      lookupFilter: (uid=${sub})
      noMatchOU: oidc
      responseType: code
      scope: openid email profile
      uidAttr: sub
      userLookupClassName: com.tremolosecurity.unison.proxy.auth.openidconnect.loadUser.LoadJWTFromAccessToken
    required: required
    secretParams:
    - name: secretid
      secretKey: OIDC_CLIENT_SECRET
      secretName: orchestra-secrets-source#[openunison.static-secret.suffix]
    - name: clientid
      secretKey: OIDC_CLIENT_ID
      secretName: orchestra-secrets-source
  - name: map
    params:
      map:
      - uid|composite|${upn}
      - mail|composite|${email}
      - givenName|composite|${given_name}
      - sn|composite|${family_name}
      - displayName|composite|${name}
      - memberOf|user|roles
    required: required
  - name: include
    params:
      chainName: azuread-load-groups
    required: required
  - name: jit
    params:
      nameAttr: uid
      workflowName: jitdb
    required: required
  - name: genoidctoken
    params:
      idpName: k8sidp
      trustName: kubernetes
    required: required
  level: 20
  root: o=Data
```

**Comment by mlbiam** [comment]
Just to validate, your `orchestra-secrets-source` `Secret` has a key called `OIDC_CLIENT_ID`?

**Comment by sandeep-ongit** [comment]
@mlbiam  - yes, it has OIDC_CLIENT_ID

```shell
kubectl describe secrets -n openunison orchestra-secrets-source 
Name:         orchestra-secrets-source
Namespace:    openunison
Labels:       app.kubernetes.io/instance=k8s-cls-2-ou
              reconcile.external-secrets.io/created-by=8c20ca3c60e35aef45444bdf396b8624
Annotations:  argocd.argoproj.io/sync-wave: -1
              reconcile.external-secrets.io/data-hash: 8762e50875f561e901c3607a6f9772f3

Type:  Opaque

Data
====
K8S_DB_SECRET:           25 bytes
OIDC_CLIENT_ID:          36 bytes
OIDC_CLIENT_SECRET:      40 bytes
unisonKeystorePassword:  30 bytes
```

**Comment by sandeep-ongit** [comment]
@mlbiam - do we know what is causing this?

**Comment by mlbiam** [comment]
OH!  i think i see the issue now.  The client id from secret needs to extend to the provisioning target.  i've got a test bed setup, stand by.

**Comment by mlbiam** [comment]
@sandeep-ongit grap the latest charts and upgrade `orchestra-login-azuread`, the version should be 1.0.4

**Comment by sandeep-ongit** [comment]
@mlbiam - Yes, I verified and it works as expected.
Thanks!
