### ISSUE TITLE
Confusion migrating from SAML2 chart

### ISSUE THREAD

**Issue by luka5** [OpenUnison/helm-charts#34]
Hi,

we are currently working on migrating our installations with SAML2 to the new helm chart structure. I've successfully migrated to the new `orchestra` chart and needed to adjust our `values.yaml` to include a self-hosted image for `precheck` and `html`.

For testing purpose, I kept using the `tremolosecurity/openunison-k8s-login-saml2:latest` image and (after adjusting the probes to us `check_alive.py`) everything works fine. Now I want to replace this image with `tremolosecurity/openunison-k8s:latest`, but I'm failing with the following error message. To migrate, I've deleted all helm charts and the namespace, before creating everything again, including the new `orchestra-login-portal` chart as described in https://openunison.github.io/deployauth/.

```
[2022-02-09 13:18:26,759][XNIO-1 task-3] INFO  AccessLog - [AzSuccess] - k8sidp - https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration - uid=Anonymous,o=Tremolo - NONE [127.0.0.1] - [f499dfb5bb7b7a1144a5dbe99a2aa2451cc01130c]
[2022-02-09 13:18:31,968][XNIO-1 task-3] INFO  AccessLog - [AzSuccess] - root-redirect - https://access-portal.mydomain.example/ - uid=Anonymous,o=Tremolo - scale-redirect [10.251.4.64] - [f64081e4c8763bf08f9aaea27afc699010851fa15]
[2022-02-09 13:18:32,021][XNIO-1 task-3] INFO  AccessLog - [Error] - completelogin - https://access-portal.mydomain.example/login/auth - cn=none - NONE [10.251.4.64] - [f925106ad8806daac7d329d444c87620d35211663]
[2022-02-09 13:18:32,021][XNIO-1 task-3] ERROR ConfigSys - Could not process request
java.lang.NullPointerException: null
        at com.tremolosecurity.proxy.auth.SAML2Auth.initializeSSO(SAML2Auth.java:361) ~[unison-server-core-1.0.25.jar:?]
        at com.tremolosecurity.proxy.auth.SAML2Auth.doGet(SAML2Auth.java:235) ~[unison-server-core-1.0.25.jar:?]
        at com.tremolosecurity.proxy.auth.sys.AuthManagerImpl.execAuth(AuthManagerImpl.java:452) ~[unison-server-core-1.0.25.jar:?]
        at com.tremolosecurity.proxy.auth.sys.AuthManagerImpl.nextAuth(AuthManagerImpl.java:134) ~[unison-server-core-1.0.25.jar:?]
        at com.tremolosecurity.proxy.auth.AuthSys.doAuth(AuthSys.java:118) ~[unison-server-core-1.0.25.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:105) ~[unison-server-core-1.0.25.jar:?]
        at com.tremolosecurity.proxy.ConfigSys.doConfig(ConfigSys.java:296) [unison-server-core-1.0.25.jar:?]
        at com.tremolosecurity.embedd.NextEmbSys.nextSys(NextEmbSys.java:93) [unison-server-core-1.0.25.jar:?]
        at com.tremolosecurity.filter.UnisonServletFilter.doFilter(UnisonServletFilter.java:299) [unison-server-core-1.0.25.jar:?]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) [undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) [undertow-core-2.2.14.Final.jar:2.2.14.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) [undertow-core-2.2.14.Final.jar:2.2.14.Final]
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) [jboss-threads-2.3.3.Final.jar:2.3.3.Final]
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) [xnio-api-3.8.5.Final.jar:3.8.5.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

Somehow I do not get redirected to our SAML, but instead fail in https://github.com/TremoloSecurity/OpenUnison/blob/790a14702bce039f82c504d1aacb95c52f607ab0/unison/unison-server-core/src/main/java/com/tremolosecurity/proxy/auth/SAML2Auth.java#L361 

Do you know what my mistake is here?

Thanks a lot!

**Comment by mlbiam** [comment]
> Do you know what my mistake is here?

None!  You found a bug in OpenUnison (linked above).  I'll get a new release out quickly to fix, but in the mean time as a workaround:

1. get the latest version of the charts :`helm repo update` - `orchestra-login-portal` should be at 2.2.2
2. In your values.yaml add `saml.authnCtxClassRef` to your values.yaml with the specific authnContextClassRef you want to use (for instance `urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport`).
3. Optional - If your IDP doesn't include an SingleLogout URL, add `saml.logoutRedirectUrl: https://#[OU_HOST]/logout` to your values.yaml

Finally, upgrade your `orchestra-login-portal` deployment and try logging in again

(ps: You may want to pull in the latest openunison-k8s image, fixed a bug that was causing the SP metadata wasn't being generated)

**Comment by luka5** [comment]
Thanks for your response, according to https://github.com/OpenUnison/helm-charts/blob/master/orchestra-login-portal/Chart.yaml#L18 the latest released `orchestra-login-portal` chart version is `2.2.1`.

I'm having a hard time understanding how the values `saml.authnCtxClassRef` or `saml.logoutRedirectUrl` are used in either this helm chart or in the latest `orchestra` chart. How are they consumed? Are they?

**Comment by mlbiam** [comment]
> Thanks for your response, according to https://github.com/OpenUnison/helm-charts/blob/master/orchestra-login-portal/Chart.yaml#L18 the latest released orchestra-login-portal chart version is 2.2.1.

sorry, we forgot to merge into the openunison repo.  It's now updated

> I'm having a hard time understanding how the values saml.authnCtxClassRef or saml.logoutRedirectUrl are used in either this helm chart or in the latest orchestra chart. How are they consumed? Are they?

They're included in https://github.com/OpenUnison/helm-charts/blob/27e466791047132778d3e7c390a22c32a924da14/orchestra-login-portal/templates/openunison/authentication_chains/standard-chains.yaml#L132 and https://github.com/OpenUnison/helm-charts/blob/27e466791047132778d3e7c390a22c32a924da14/orchestra-login-portal/templates/openunison/authentication_chains/standard-chains.yaml#L144

it's a workaround so that those configuration options aren't interpreted as `Null` by openunison until we fix https://github.com/TremoloSecurity/OpenUnison/issues/614

**Comment by luka5** [comment]
Thanks again, I can confirm that the workaround option 2 (setting `saml.authnCtxClassRef`) worked fine for me.

**Comment by mlbiam** [comment]
1.0.26 has been released.  re-rollingout your `Deployment` will update to a permanent fix
