### ISSUE TITLE
SecurityContext in helm charts

### ISSUE THREAD

**Issue by kgrozdanov** [OpenUnison/helm-charts#89]
I tried to install recently the helm charts manually as described in the documentation. Our kubernetes cluster has  policies, which are quite strict and prohibit creation of pods if we don't set proper securityContext for pods and containers. I had to edit a lot of  templates to add securityContext in order to be able to deploy. The values file for orchestra deployment is attached
[values-orchestra.yml.zip](https://github.com/OpenUnison/helm-charts/files/11341567/values-orchestra.yml.zip)

Is it possible to add the securityContext in the templates and make it configurable in the values.yaml? It should be made for all deployments, jobs, test containers, etc. 

From my experience, the pods did not need any elevated privileges and are running fine.  Here is the context I used:

pod:
```yaml
securityContext:
        fsGroup: 10001
        supplementalGroups: [10001]
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
```
container:
```yaml
securityContext:
          allowPrivilegeEscalation: false
```

As a second point I tried to deploy in a namespace which was exempted from these policies, but it was not successful. The orchestra pod couldn't start and this was the error in the pod:

```
com.tremolosecurity.provisioning.core.ProvisioningException: Could not load CRDs
	at com.tremolosecurity.k8s.watch.K8sWatcher.initalRun(K8sWatcher.java:176)
	at com.tremolosecurity.provisioning.targets.LoadTargetsFromK8s.loadDynamicTargets(LoadTargetsFromK8s.java:223)
	at com.tremolosecurity.provisioning.core.ProvisioningEngineImpl.generateTargets(ProvisioningEngineImpl.java:887)
	at com.tremolosecurity.provisioning.core.ProvisioningEngineImpl.<init>(ProvisioningEngineImpl.java:482)
	at com.tremolosecurity.config.util.UnisonConfigManagerImpl.initialize(UnisonConfigManagerImpl.java:484)
	at com.tremolosecurity.filter.UnisonServletFilter.init(UnisonServletFilter.java:369)
	at com.tremolosecurity.openunison.OpenUnisonServletFilter.init(OpenUnisonServletFilter.java:118)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
	at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:86)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:594)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
	at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.main(OpenUnisonOnUndertow.java:353)
Caused by: java.io.IOException: Unexpected result calling 'https://10.102.0.1:443/apis/openunison.tremolo.io/v1/namespaces/openunison/targets' - 403 / {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"targets.openunison.tremolo.io is forbidden: User \"system:serviceaccount:infra-services:openunison-orchestra\" cannot list resource \"targets\" in API group \"openunison.tremolo.io\" in the namespace \"openunison\"","reason":"Forbidden","details":{"group":"openunison.tremolo.io","kind":"targets"},"code":403}

	at com.tremolosecurity.unison.openshiftv3.OpenShiftTarget.callWS(OpenShiftTarget.java:516)
	at com.tremolosecurity.k8s.watch.K8sWatcher.initalRun(K8sWatcher.java:109)
	... 14 more
Exception in thread "main" javax.servlet.ServletException: com.tremolosecurity.provisioning.core.ProvisioningException: Could not load CRDs
	at com.tremolosecurity.filter.UnisonServletFilter.init(UnisonServletFilter.java:400)
	at com.tremolosecurity.openunison.OpenUnisonServletFilter.init(OpenUnisonServletFilter.java:118)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:111)
	at io.undertow.servlet.core.ManagedFilter.createFilter(ManagedFilter.java:86)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:594)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
	at com.tremolosecurity.openunison.undertow.OpenUnisonOnUndertow.main(OpenUnisonOnUndertow.java:353)
Caused by: com.tremolosecurity.provisioning.core.ProvisioningException: Could not load CRDs
	at com.tremolosecurity.k8s.watch.K8sWatcher.initalRun(K8sWatcher.java:176)
	at com.tremolosecurity.provisioning.targets.LoadTargetsFromK8s.loadDynamicTargets(LoadTargetsFromK8s.java:223)
	at com.tremolosecurity.provisioning.core.ProvisioningEngineImpl.generateTargets(ProvisioningEngineImpl.java:887)
	at com.tremolosecurity.provisioning.core.ProvisioningEngineImpl.<init>(ProvisioningEngineImpl.java:482)
	at com.tremolosecurity.config.util.UnisonConfigManagerImpl.initialize(UnisonConfigManagerImpl.java:484)
	at com.tremolosecurity.filter.UnisonServletFilter.init(UnisonServletFilter.java:369)
	... 9 more
Caused by: java.io.IOException: Unexpected result calling 'https://10.102.0.1:443/apis/openunison.tremolo.io/v1/namespaces/openunison/targets' - 403 / {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"targets.openunison.tremolo.io is forbidden: User \"system:serviceaccount:infra-services:openunison-orchestra\" cannot list resource \"targets\" in API group \"openunison.tremolo.io\" in the namespace \"openunison\"","reason":"Forbidden","details":{"group":"openunison.tremolo.io","kind":"targets"},"code":403}

	at com.tremolosecurity.unison.openshiftv3.OpenShiftTarget.callWS(OpenShiftTarget.java:516)
	at com.tremolosecurity.k8s.watch.K8sWatcher.initalRun(K8sWatcher.java:109)
	... 14 more
```

As you see in the error, it still tried to call openunison namespace even when deployed in a different one.

**Comment by kgrozdanov** [comment]
Ok, to be more precise here I made 3 attempts:

1. with ouctl - unsuccessful, because of missing securityContext. The policies did not permit the creation of any pods.
2. In a namespace infra-services which is excluded from policy checks - they I had the error I pasted in the ticket. Our cluster is RBAC enabled, the problem is that openunison was installed in another namespace and openunison namespace didn't even exist. Still the app was calling https://10.102.0.1:443/apis/openunison.tremolo.io/v1/namespaces/**openunison**/targets and it should be https://10.102.0.1:443/apis/openunison.tremolo.io/v1/namespaces/**infra-services**/targets (I may be wrong here, but this is how I interpret it).
3. After 2 failing attempts I decided to pull the charts, edit the templates to add securityContext and deploy manually with the local copies of the charts. This third attempt succeeded and the application was installed in openunison namespace. 

So you are correct, the second error is not related to security context, but if I interpret it correctly it is also not RBAC problem, simply because it is trying to call the API for the openunison namespace, and the RBAC is configured for the infra-services namespace.

**Comment by kgrozdanov** [comment]
Hi,
Thank you for the quick reaction.

There are issues - operator fails with the following message in the log:
```
Error: Unable to access jarfile /usr/local/ouoperator/ouoperator.jar
```

Also the test pod https://github.com/OpenUnison/helm-charts/blob/master/orchestra/templates/tests/precheck.yaml in orchestra chart is missing the security context.

**Comment by mlbiam** [comment]
> Error: Unable to access jarfile /usr/local/ouoperator/ouoperator.jar

That's odd.  I can't reproduce.  What's the `Image ID` from `k describe pod -l app=openunison-operator -n openunison`?

Also, what other policies do you have in place beyond `securtiyContext`? What are you using to enforce policies (Gatekeeper/Kyverno/etc)?

> Also the test pod https://github.com/OpenUnison/helm-charts/blob/master/orchestra/templates/tests/precheck.yaml in orchestra chart is missing the security context.

fixed.  new `orchestra` chart is pushed with version 2.10.20

**Comment by kgrozdanov** [comment]
This is what  I have:
```yaml
containers:
  openunison-operator:
    Container ID:  containerd://e8bf4634d6ead5f262ceba306a1823c333e92b734b04f2019b89f1d0118026e2
    Image:         docker.io/tremolosecurity/openunison-k8s-operator:latest
    Image ID:      docker.io/tremolosecurity/openunison-k8s-operator@sha256:67ba6ed5cecb50ab88e8b16eadafb3d1464870018712444dd037927712c9fd37
```
Regarding policies - we use Gatekeeper (this comes from Azure), but it acts only on pod admission.

**Comment by mlbiam** [comment]
> `docker.io/tremolosecurity/openunison-k8s-operator:latest`

odd, this is the old version (we recently just released a new operator with a new image).  What do you have in `helm list -n openunison`?  Try adding

```yaml
operator:
  image: `docker.io/tremolosecurity/openunison-kubernetes-operator:latest`
```

to your values.yaml.

> Regarding policies - we use Gatekeeper (this comes from Azure), but it acts only on pod admission.

Can you provide the policy used?  I'd like to reproduce your environment (assuming the correct image doesn't fix the issue)

**Comment by kgrozdanov** [comment]
I deployed the charts so it should be fine.

**Comment by mlbiam** [comment]
Awesome. Can we close out the issue?

**Comment by kgrozdanov** [comment]
I think yes
